version: '3.7'

services:
  nginx:
    image: chaberb/nginx-ssl
    depends_on:
      - cdn
      - web
    ports:
      - "443:443"
    volumes:
      - ./nginx-uwsgi.conf:/etc/nginx/nginx.conf

  web:
    build: web
    volumes:
      - ./web:/var/www/app
    depends_on:
      - redis
    environment:
      - FLASK_DEBUG=True
    ports:
      - "5001:5000"

  cdn:
    image: chaberb/flask-jwt
    volumes:
      - ./cdn:/var/www/app
      - ./tmp:/tmp
    ports:
      - "5002:5000"

  redis:
    image: redis
    ports:
      - "6379:6379"
